spring:
  application:
    name: g145-market

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=g145market
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml

  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
server:
  port: 8088