spring:

  application:
    name: g145-market

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=g145market
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update