-- liquibase formatted sql

-- changeset magzhan:1
CREATE TABLE IF NOT EXISTS COMMENTS
(
    COMMENT_ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    COMMENT_TEXT TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT USER_KEY FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
    );
