-- liquibase formatted sql

-- changeset kazybek:1

CREATE TABLE IF NOT EXISTS tasklogs
(
    LOG_ID BIGINT PRIMARY KEY,
    TASK_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    ACTION VARCHAR(177) NOT NULL,
    PREVIOUS_VALUE VARCHAR (200),
    NEW_VALUES VARCHAR (255),
    CREATED_AT DATETIME NOT NULL
    );