-- liquibase formatted sql

-- changeset magzhan:1
CREATE TABLE IF NOT EXISTS COMMENTS
(
    COMMENT_ID SERIAL PRIMARY KEY,
    COMMENT_TEXT TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);
