CREATE TABLE IF NOT EXISTS STUDENTS
(
    ID        BIGSERIAL PRIMARY KEY NOT NULL,
    FULL_NAME VARCHAR(255)          NOT NULL,
    AGE       INT
);

CREATE TABLE IF NOT EXISTS STUDENTS_ACADEMIES
(
    STUDENT_ID INT,
    ACADEMY_ID INT,
    PRIMARY KEY (STUDENT_ID, ACADEMY_ID),
    CONSTRAINT FK_STUDENT_ID FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS (ID),
    CONSTRAINT FK_ACADEMY_ID FOREIGN KEY (ACADEMY_ID) REFERENCES ACADEMIES (ID)
)