CREATE TABLE IF NOT EXISTS CITIES
(
    ID   BIGSERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR(50) UNIQUE    NOT NULL,
    CODE VARCHAR(3)
);

CREATE TABLE IF NOT EXISTS ACADEMIES
(
    ID      BIGSERIAL PRIMARY KEY NOT NULL,
    NAME    VARCHAR(50) UNIQUE    NOT NULL,
    COURSE  VARCHAR(30)           NOT NULL,
    RATING  DOUBLE PRECISION,
    CITY_ID BIGSERIAL,
    CONSTRAINT FK_ACADEMIES_CITY
        FOREIGN KEY (CITY_ID)
            REFERENCES CITIES (ID)
)