spring.application.name=g139-jpa

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/g139?currentSchema=jpa
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update