spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=g130migrationpractice
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:/db/changelog/changelog.xml